export const customSelectPriceStyles = {
  control: (provided) => ({
    ...provided,
    borderRadius: "12px",
    width: "196px",
    height: "44px",
    background: "#f7f7f7",
    fontFamily: "Manrope, sans-serif",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: 1.25,
    color: "#101828",
    boxShadow: "none",
    cursor: "pointer",
    border: 0,
  }),
  option: (provided, state) => ({
    ...provided,
    fontFamily: "Manrope, sans-serif",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: 1.25,
    color: state.isSelected ? "#101828" : "#8d929a",
    backgroundColor: "#fff",
    cursor: "pointer",
    ":active": {
      backgroundColor: "#fff",
    },
    marginBottom: "8px",
    padding: "0 18px",
    ":last-child": {
      marginBottom: 0,
    },
  }),
  menu: (provided) => ({
    ...provided,
    padding: "14px 0",
    borderRadius: "12px",
    width: "196px",
    border: "1px solid #f7f7f7",
    boxShadow: "0 4px 36px 0 rgba(0, 0, 0, 0.02)",
  }),
  menuList: (provided) => ({
    ...provided,
    maxHeight: "160px",
    width: "196px",
    overflowY: "auto",
  }),
  singleValue: (provided) => ({
    ...provided,
    fontFamily: "Manrope, sans-serif",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: 1.25,
    color: "#101828",
  }),
  placeholder: (provided) => ({
    ...provided,
    fontFamily: "Manrope, sans-serif",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: 1.25,
    color: "#101828",
  }),
};
